/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-model.gltf')
  const meshRef = useRef();

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }

    meshRef.current.rotation.x += 0.003;
    meshRef.current.rotation.y += 0.003;
  });
  return (
    <group {...props} dispose={null}>
      <mesh ref={meshRef} geometry={nodes.mesh_0.geometry}>
      <meshLambertMaterial attach="material" color="blue" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d-model.gltf')
