/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export function InnerModel(props) {
  const { nodes } = useGLTF('/3d-model.gltf')
  const meshRef = useRef();

  useFrame(() => {
    if (!meshRef.current) {
      return;
    }

    meshRef.current.rotation.x -= 0.002;
    meshRef.current.rotation.y -= 0.008;
  });
  return (
    <group {...props} dispose={null}>
      <mesh ref={meshRef} geometry={nodes.mesh_0.geometry} castShadow>
      <meshPhongMaterial color="#33bbcf" shininess={1} opacity={0.8} transparent/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d-model.gltf')
