/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import {scaleAcceleration} from './App.js';

export function InnerModel(props) {
  const { nodes } = useGLTF('/3d-model.gltf')
  const meshRef = useRef();
  let scale = 0.25;
  useFrame(() => {
    if (!meshRef.current) {
      return;
    }
    meshRef.current.rotation.x -= 0.002;
    meshRef.current.rotation.y -= 0.008;
    meshRef.current.scale.x += scaleAcceleration;
    meshRef.current.scale.y += scaleAcceleration;
    meshRef.current.scale.z += scaleAcceleration;
  });

  return (
    <group {...props} dispose={null}>
      <mesh scale={scale} ref={meshRef} geometry={nodes.mesh_0.geometry} castShadow>
      <meshPhysicalMaterial color="#33bbcf" opacity={0.9} transparent/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d-model.gltf')
